//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transform.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transform.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;zerno:MessageData Id=&quot;SIGNED_BY_CALLER&quot; xmlns:zerno=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/types/1.0.1&quot; xmlns:dicts=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/dictionaries/1.0.1&quot;&gt;
        ///  &lt;zerno:MessageID&gt;3eb6773e-fed4-11ec-b786-e2b1cb7e6353&lt;/zerno:MessageID&gt;
        ///  &lt;zerno:ReferenceMessageID&gt;3eb6773e-fed4-11ec-b786-e2b1cb7e6353&lt;/zerno:ReferenceMessageID&gt;
        ///  &lt;zerno:MessagePrimaryContent&gt;
        ///    &lt;dicts:Request&gt;
        ///      &lt;dicts:Dictionary&gt;OKPD2Type&lt;/dicts:Dictionary&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string OKPD2TypeRequest {
            get {
                return ResourceManager.GetString("OKPD2TypeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCanceledExtinctionRefusal extinctionRefusalId=&quot;100&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot;/&gt;.
        /// </summary>
        internal static string RequestCanceledExtinctionRefusal {
            get {
                return ResourceManager.GetString("RequestCanceledExtinctionRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCanceledLot lotNumber=&quot;string&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/lots/1.0.0&quot;/&gt;.
        /// </summary>
        internal static string RequestCanceledLot {
            get {
                return ResourceManager.GetString("RequestCanceledLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string RequestCanceledSDIZ {
            get {
                return ResourceManager.GetString("RequestCanceledSDIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCreateExtinction SDIZNumber=&quot;string&quot; amount=&quot;100&quot; fullExtinction=&quot;false&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/sdiz/1.0.0&quot; xmlns:ns2=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/common/1.0.0&quot;&gt;
        ///  &lt;!--Zero or more repetitions:--&gt;
        ///  &lt;ns1:TransportInfo numberTransport=&quot;string&quot; numberСontainer=&quot;string&quot;&gt;
        ///    &lt;ns2:TransportCode&gt;string&lt;/ns2:TransportCode&gt;
        ///  &lt;/ns1:TransportInfo&gt;
        ///  &lt;!--Optional:--&gt;
        ///  &lt;ns1:WeightDisc [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RequestCreateExtinction {
            get {
                return ResourceManager.GetString("RequestCreateExtinction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCreateExtinctionRefusal SDIZNumber=&quot;string&quot; amount=&quot;100&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/sdiz/1.0.0&quot;&gt;
        ///  &lt;!--Optional:--&gt;
        ///  &lt;ns1:LotReturnReasonCode&gt;string&lt;/ns1:LotReturnReasonCode&gt;
        ///  &lt;!--Optional:--&gt;
        ///  &lt;ns1:CauseComment&gt;string&lt;/ns1:CauseComment&gt;
        ///&lt;/ns:RequestCreateExtinctionRefusal&gt;.
        /// </summary>
        internal static string RequestCreateExtinctionRefusal {
            get {
                return ResourceManager.GetString("RequestCreateExtinctionRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCreateLot xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/lots/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/lots/1.0.0&quot; xmlns:ns2=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/organizations/1.0.0&quot; xmlns:ns3=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/common/1.0.0&quot;&gt;
        ///  &lt;!--You have a CHOICE of the next 5 items at this level--&gt;
        ///  &lt;ns1:LotFromAnother&gt;
        ///    &lt;!--1 or more repetitions:--&gt;
        ///    &lt;ns1:ParentLot lotNumber=&quot;string&quot; amount=&quot;100&quot;/&gt;
        ///  &lt;/ns1:LotFromAnother&gt;
        ///  &lt;ns1:L [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RequestCreateLot {
            get {
                return ResourceManager.GetString("RequestCreateLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCreateLotDebit amount=&quot;100&quot; lotNumber=&quot;string&quot; comment=&quot;string&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/lots/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/lots/1.0.0&quot;&gt;
        ///  &lt;ns1:Reason&gt;string&lt;/ns1:Reason&gt;
        ///&lt;/ns:RequestCreateLotDebit&gt;.
        /// </summary>
        internal static string RequestCreateLotDebit {
            get {
                return ResourceManager.GetString("RequestCreateLotDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCreateLotOnElevator xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/lots/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/lots/1.0.0&quot; xmlns:ns2=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/organizations/1.0.0&quot; xmlns:ns3=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/common/1.0.0&quot;&gt;
        ///  &lt;!--You have a CHOICE of the next 5 items at this level--&gt;
        ///  &lt;ns1:LotFromAnother&gt;
        ///    &lt;!--1 or more repetitions:--&gt;
        ///    &lt;ns1:ParentLot lotNumber=&quot;string&quot; amount=&quot;100&quot;/&gt;
        ///  &lt;/ns1:LotFromAnother&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RequestCreateLotOnElevator {
            get {
                return ResourceManager.GetString("RequestCreateLotOnElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCreateSDIZ lotNumber=&quot;string&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/sdiz/1.0.0&quot; xmlns:ns2=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/organizations/1.0.0&quot; xmlns:ns3=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/common/1.0.0&quot;&gt;
        ///  &lt;!--You have a CHOICE of the next 3 items at this level--&gt;
        ///  &lt;ns1:OperationInRF&gt;
        ///    &lt;!--1 to 4 repetitions:--&gt;
        ///    &lt;ns1:OperationSDIZ&gt;SHIPPING&lt;/ns1:OperationSDIZ&gt;
        ///    &lt;!--Optional:- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RequestCreateSDIZ {
            get {
                return ResourceManager.GetString("RequestCreateSDIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestCreateSDIZElevator lotNumber=&quot;string&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/sdiz/1.0.0&quot; xmlns:ns2=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/organizations/1.0.0&quot;&gt;
        ///  &lt;ns1:OperationSDIZElevator&gt;
        ///    &lt;!--You have a CHOICE of the next 2 items at this level--&gt;
        ///    &lt;ns1:AcceptanceElevator dateDogovor=&quot;2008-09-29&quot; NumberDogovor=&quot;string&quot; storageArea=&quot;1.5E2&quot; storagePeriod=&quot;2014-09-19&quot; storageСonditions=&quot;string&quot;&gt;
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RequestCreateSDIZElevator {
            get {
                return ResourceManager.GetString("RequestCreateSDIZElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestGetListExtinction sdizNumber=&quot;string&quot; dateFrom=&quot;2008-09-29&quot; dateTo=&quot;2014-09-19&quot; status=&quot;SUBSCRIBED&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot;/&gt;.
        /// </summary>
        internal static string RequestGetListExtinction {
            get {
                return ResourceManager.GetString("RequestGetListExtinction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestGetListExtinctionRefusal sdizNumber=&quot;string&quot; dateFrom=&quot;2008-09-29&quot; dateTo=&quot;2014-09-19&quot; status=&quot;SUBSCRIBED&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot;/&gt;.
        /// </summary>
        internal static string RequestGetListExtinctionRefusal {
            get {
                return ResourceManager.GetString("RequestGetListExtinctionRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestGetListLot dateFrom=&quot;2008-09-29&quot; dateTo=&quot;2014-09-19&quot; lotNumber=&quot;string&quot; lotID=&quot;100&quot; status=&quot;CANCELED&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/lots/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/organizations/1.0.0&quot;&gt;
        ///  &lt;!--Optional:--&gt;
        ///  &lt;ns:OKPD2&gt;string&lt;/ns:OKPD2&gt;
        ///  &lt;!--Optional:--&gt;
        ///  &lt;ns:Owner&gt;
        ///    &lt;!--You have a CHOICE of the next 4 items at this level--&gt;
        ///    &lt;!--Optional:--&gt;
        ///    &lt;ns1:LegalEntity&gt;
        ///      &lt;ns1:Name&gt;string&lt;/ns1:Name&gt;
        ///      &lt;!--Optional:--&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RequestGetListLot {
            get {
                return ResourceManager.GetString("RequestGetListLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestGetListLotDebit lotNumber=&quot;string&quot; dateFrom=&quot;2008-09-29&quot; dateTo=&quot;2014-09-19&quot; status=&quot;SUBSCRIBED&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/lots/1.0.0&quot;/&gt;.
        /// </summary>
        internal static string RequestGetListLotDebit {
            get {
                return ResourceManager.GetString("RequestGetListLotDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestGetListSDIZ dateFrom=&quot;2008-09-29&quot; dateTo=&quot;2014-09-19&quot; lotNumber=&quot;string&quot; sdizNumber=&quot;string&quot; sdizID=&quot;100&quot; status=&quot;CANCELED&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot; xmlns:ns1=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/organizations/1.0.0&quot;&gt;
        ///  &lt;!--Optional:--&gt;
        ///  &lt;ns:OKPD2&gt;string&lt;/ns:OKPD2&gt;
        ///  &lt;!--Optional:--&gt;
        ///  &lt;ns:Owner&gt;
        ///    &lt;!--You have a CHOICE of the next 4 items at this level--&gt;
        ///    &lt;!--Optional:--&gt;
        ///    &lt;ns1:LegalEntity&gt;
        ///      &lt;ns1:Name&gt;string&lt;/ns1:Name&gt;
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RequestGetListSDIZ {
            get {
                return ResourceManager.GetString("RequestGetListSDIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ns:RequestGetListSDIZElevator dateFrom=&quot;2008-09-29&quot; dateTo=&quot;2014-09-19&quot; lotNumber=&quot;string&quot; sdizNumber=&quot;string&quot; sdizID=&quot;100&quot; status=&quot;CANCELED&quot; xmlns:ns=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/sdiz/1.0.0&quot;&gt;
        ///  &lt;!--Optional:--&gt;
        ///  &lt;ns:OKPD2&gt;string&lt;/ns:OKPD2&gt;
        ///&lt;/ns:RequestGetListSDIZElevator&gt;.
        /// </summary>
        internal static string RequestGetListSDIZElevator {
            get {
                return ResourceManager.GetString("RequestGetListSDIZElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/css&quot; href=&quot;style.css&quot;?&gt;
        ///&lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        /// &lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot;&gt;yes!&lt;/myns:rty&gt;
        /// &lt;iop value=&quot;yes, yes!&quot;/&gt;
        ///&lt;/qwe&gt;.
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        ///&lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot;&gt;yes!&lt;/myns:rty&gt;
        ///&lt;iop value=&quot; test &quot;/&gt;     &lt;/qwe&gt;
        ///.
        /// </summary>
        internal static string Test3 {
            get {
                return ResourceManager.GetString("Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        /// &lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot;&gt;yes!&lt;/myns:rty&gt;
        /// &lt;iop value=&quot;yes, yes!&quot;/&gt;
        ///&lt;/qwe&gt;.
        /// </summary>
        internal static string Test4 {
            get {
                return ResourceManager.GetString("Test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        ///  &lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot; myns:nouse=&quot;http://nouse&quot;&gt;yes!&lt;/myns:rty&gt;
        ///  &lt;iop value=&quot;yes, yes!&quot; /&gt;
        ///&lt;/qwe&gt;.
        /// </summary>
        internal static string Test5 {
            get {
                return ResourceManager.GetString("Test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        /// &lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot;&gt;yes!&lt;/myns:rty&gt;
        /// &lt;iop value=&quot;yes, yes!&quot;/&gt;
        ///&lt;/qwe&gt;.
        /// </summary>
        internal static string Test6 {
            get {
                return ResourceManager.GetString("Test6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;nns:x xmlns:nns=&quot;http://a&quot; attrB=&quot;value1&quot; attrA=&quot;value2&quot;&gt;
        /// &lt;y xmlns=&quot;http://a&quot;&gt;yes!&lt;/y&gt;
        ///&lt;/nns:x&gt;.
        /// </summary>
        internal static string Test7 {
            get {
                return ResourceManager.GetString("Test7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;tns:PERNAMEZPRequest xmlns:markcont=&quot;urn://x-artefacts-zags-pernamezp/markertypes/4.0.0&quot; xmlns:tns=&quot;urn://x-artefacts-zags-pernamezp/4.0.0&quot; xmlns:fnst=&quot;urn://x-artefacts-zags-pernamezp/types/4.0.0&quot;  xmlns:frgu=&quot;urn://x-artefacts-zags-pernamezp/frgutypes/4.0.0&quot; markcont:РўРёРїР—Р°СЏРІР»=&quot;Р¤Р›&quot; Р—Р°СЏРІР»Р”Р°С‚Р°=&quot;2019-08-13&quot; tns:РРґРЎРІРµРґ=&quot;a&quot; markcont:Р—Р°СЏРІР»РµРЅРёРµ=&quot;15843&quot; Р”Р°С‚Р°РЎРІРµРґ=&quot;2018-08-13&quot; frgu:РљРѕРґРЈСЃР»СѓРіРё=&quot;3482943&quot;/&gt;.
        /// </summary>
        internal static string Test8 {
            get {
                return ResourceManager.GetString("Test8", resourceCulture);
            }
        }
    }
}
