//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transform.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transform.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;zerno:MessageData Id=&quot;SIGNED_BY_CALLER&quot; xmlns:zerno=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/types/1.0.1&quot; xmlns:dicts=&quot;urn://x-artefacts-mcx-gov-ru/fgiz-zerno/api/ws/dictionaries/1.0.1&quot;&gt;
        ///  &lt;zerno:MessageID&gt;3eb6773e-fed4-11ec-b786-e2b1cb7e6353&lt;/zerno:MessageID&gt;
        ///  &lt;zerno:ReferenceMessageID&gt;3eb6773e-fed4-11ec-b786-e2b1cb7e6353&lt;/zerno:ReferenceMessageID&gt;
        ///  &lt;zerno:MessagePrimaryContent&gt;
        ///    &lt;dicts:Request&gt;
        ///      &lt;dicts:Dictionary&gt;OKPD2Type&lt;/dicts:Dictionary&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string OKPD2TypeRequest {
            get {
                return ResourceManager.GetString("OKPD2TypeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/css&quot; href=&quot;style.css&quot;?&gt;
        ///&lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        /// &lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot;&gt;yes!&lt;/myns:rty&gt;
        /// &lt;iop value=&quot;yes, yes!&quot;/&gt;
        ///&lt;/qwe&gt;.
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        ///&lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot;&gt;yes!&lt;/myns:rty&gt;
        ///&lt;iop value=&quot; test &quot;/&gt;     &lt;/qwe&gt;
        ///.
        /// </summary>
        internal static string Test3 {
            get {
                return ResourceManager.GetString("Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        /// &lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot;&gt;yes!&lt;/myns:rty&gt;
        /// &lt;iop value=&quot;yes, yes!&quot;/&gt;
        ///&lt;/qwe&gt;.
        /// </summary>
        internal static string Test4 {
            get {
                return ResourceManager.GetString("Test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        ///  &lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot; myns:nouse=&quot;http://nouse&quot;&gt;yes!&lt;/myns:rty&gt;
        ///  &lt;iop value=&quot;yes, yes!&quot; /&gt;
        ///&lt;/qwe&gt;.
        /// </summary>
        internal static string Test5 {
            get {
                return ResourceManager.GetString("Test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;qwe xmlns=&quot;http://t.e.s.t&quot;&gt;
        /// &lt;myns:rty xmlns:myns=&quot;http://y.e.s&quot;&gt;yes!&lt;/myns:rty&gt;
        /// &lt;iop value=&quot;yes, yes!&quot;/&gt;
        ///&lt;/qwe&gt;.
        /// </summary>
        internal static string Test6 {
            get {
                return ResourceManager.GetString("Test6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;nns:x xmlns:nns=&quot;http://a&quot; attrB=&quot;value1&quot; attrA=&quot;value2&quot;&gt;
        /// &lt;y xmlns=&quot;http://a&quot;&gt;yes!&lt;/y&gt;
        ///&lt;/nns:x&gt;.
        /// </summary>
        internal static string Test7 {
            get {
                return ResourceManager.GetString("Test7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;tns:PERNAMEZPRequest xmlns:markcont=&quot;urn://x-artefacts-zags-pernamezp/markertypes/4.0.0&quot; xmlns:tns=&quot;urn://x-artefacts-zags-pernamezp/4.0.0&quot; xmlns:fnst=&quot;urn://x-artefacts-zags-pernamezp/types/4.0.0&quot;  xmlns:frgu=&quot;urn://x-artefacts-zags-pernamezp/frgutypes/4.0.0&quot; markcont:ТипЗаявл=&quot;ФЛ&quot; ЗаявлДата=&quot;2019-08-13&quot; tns:ИдСвед=&quot;a&quot; markcont:Заявление=&quot;15843&quot; ДатаСвед=&quot;2018-08-13&quot; frgu:КодУслуги=&quot;3482943&quot;&gt;.
        /// </summary>
        internal static string Test8 {
            get {
                return ResourceManager.GetString("Test8", resourceCulture);
            }
        }
    }
}
